TOP=..
include $(TOP)/configure/CONFIG

DBDINSTALL = symb.dbd

HTMLS_DIR = .
HTMLS += devSymb.html

LIBSRCS_vxWorks += devAiSymb.c
LIBSRCS_vxWorks += devAoSymb.c
LIBSRCS_vxWorks += devBiSymb.c
LIBSRCS_vxWorks += devBoSymb.c
LIBSRCS_vxWorks += devLiSymb.c
LIBSRCS_vxWorks += devLoSymb.c
LIBSRCS_vxWorks += devMbbiSymb.c
LIBSRCS_vxWorks += devMbbiSymbRaw.c
LIBSRCS_vxWorks += devMbboSymb.c
LIBSRCS_vxWorks += devMbboSymbRaw.c
LIBSRCS_vxWorks += devSiSymb.c
LIBSRCS_vxWorks += devSoSymb.c
LIBSRCS_vxWorks += devSymbFind.c
LIBSRCS_vxWorks += devWfSymb.c

LIBRARY_vxWorks = symbLib

include $(TOP)/configure/RULES_BUILD
