TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

PROD_vxWorks = devSymbTest

include $(TOP)/configure/RULES_BUILD
#----------------------------------------
#  ADD RULES AFTER THIS LINE
